name: "API Tests"
on:
  push:
    paths:
      - "api/**"
  pull_request:
    branches: ["main"]
    paths:
      - "api/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Rust toolchain
        uses: https://github.com/dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Ensure code compiles
        run: |
          cargo build --all

      - name: Run Tests
        run: cargo test --all

      - name: Run Clippy
        run: cargo clippy --all -- -D warnings

      - name: Run Rustfmt
        run: cargo fmt --all --check
